### ISSUE TITLE
extract_form_data dies when no Content-Disposition name

### ISSUE THREAD

**Issue by lukec** [chansen/p5-http-multipartparser#2]
After upgrading to the latest Plack, our API is failing when one of our API clients tries to upload an image and provides a Content-Disposition header that features a `filename` but no `name`.  

I wish this library was cool and used the file name part of the `filename` when no name was present.

**Comment by lukec** [comment]
A few more notes.

We were bit by this when upgrading Plack.  Previously we would perform a file upload with the following header. (this no longer works)

`Content-Disposition: attachment; filename=foo.png`

With the latest code, this fails for 2 reasons:
1) the code only handles `Content-Disposition: form-data` - `Content-Disposition: attachment` is rejected. 
2) the code must have a `name` field in the Content-Disposition.

From the (limited) research I've done, both of these should be supported.

Thanks for all your help making Plack and Perl web frameworks work great.

**Comment by chansen** [comment]
This issue should have been reported in [`HTTP::Entity::Parser`](https://github.com/kazeburo/HTTP-Entity-Parser/issues), the `extract_form_data()` routine is part of that distribution.

`HTTP::Entity::Parser` (`HTTP::Entity::Parser::MultiPart`) implements a parser for the `multipart/form-data` and the specification [_RFC 7578 Returning Values from Forms: multipart/form-data_](https://tools.ietf.org/html/rfc7578) is very clear:

> 4.2.  Content-Disposition Header Field for Each Part
> 
>    Each part MUST contain a Content-Disposition header field [RFC2183]
>    where the disposition type is "form-data".  The Content-Disposition
>    header field MUST also contain an additional parameter of "name"; the
>    value of the "name" parameter is the original field name from the
>    form (possibly encoded; see Section 5.1).  For example, a part might
>    contain a header field such as the following, with the body of the
>    part containing the form data of the "user" field:
> 
>            Content-Disposition: form-data; name="user"
> 
>    For form data that represents the content of a file, a name for the
>    file SHOULD be supplied as well, by using a "filename" parameter of
>    the Content-Disposition header field.  The file name isn't mandatory
>    for cases where the file name isn't available or is meaningless or
>    private; this might result, for example, when selection or drag-and-
>    drop is used or when the form data content is streamed directly from
>    a device.

`Content-Disposition: inline` or `Content-Disposition: attachment` should only be in HTTP responses, as specified in [RFC 6266 _Use of the Content-Disposition Header Field in the Hypertext Transfer Protocol (HTTP)_](https://tools.ietf.org/html/rfc6266).

**Comment by lukec** [comment]
Thank you for this response!
